#!/usr/bin/env bash

path_list="/Users/omapdy/Site /Users/omapdy/.config"
max_depth=5
custom_selected_name="false"
selected_name="home"
if [[ $# -gt 0 ]]; then
    IFS=';' read -ra ARGS <<< $1
    for ARG in ${ARGS[@]}; do
        KEY=${ARG%%=*}
        VALUE=${ARG#*=}

        if [[ $KEY == "path" ]]; then
            path_list=$VALUE
        fi

        if [[ $KEY == "m_d" ]] && [[ $VALUE =~ ^[0-9]+$ ]]; then
            max_depth=$VALUE
        fi

        if [[ $KEY == "s_n" ]]; then
            selected_name=$VALUE
            custom_selected_name="true"
        fi
    done
fi

#selected=$(find $path_list -mindepth 1 -maxdepth $max_depth  -type d | fzf --bind tab:up,shift-tab:down )
selected=$(fd --max-depth $max_depth --type d --hidden --exclude .git --exclude node_modules --exclude vendor . $path_list | fzf --bind tab:up,shift-tab:down)

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $custom_selected_name == "false" ]]; then
    selected_name=$(basename "$selected" | tr . _)
fi

tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t $selected_name
else
    tmux attach-session -t $selected_name
fi
